{{- if .Values.dataProtection.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chatbot.fullname" . }}-data-protection
  labels:
    {{- include "chatbot.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.dataProtection.persistence.size }}
  {{- with .Values.dataProtection.persistence.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
{{- end }}