apiVersion: v1
kind: Service
metadata:
  name: {{ include "chatbot-postgres.name" . }}
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
  selector:
    {{- include "chatbot-postgres.selector" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chatbot-postgres.name" . }}-headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
  selector:
    {{- include "chatbot-postgres.selector" . | nindent 4 }}
